### ISSUE TITLE
Question Pool

### ISSUE THREAD

**Issue by ahinkle** [ahinkle/quizknows#8]
List of Questions -- we need about 10-20 random questions:

**Comment by ahinkle** [comment]
> Do you want salad or fries with that?

1. Salad
2. Fries
3. Yes
4. Nah

**Comment by ahinkle** [comment]
> Dine-In, Carry-out, or Delivery?

1. Dine-In
2. Carry-Out
3. Delivery

**Comment by ahinkle** [comment]
> You're on a stranded Island. Pick one item

1. Fishing Net
2. Giant box of matches
3. Ice Cold Beer
4. Ice Cream

**Comment by ahinkle** [comment]
> How much money are you willing to spend?

1. Money is no object.
2. I almost chose McDonalds, so close to nothing.
3. It depends on what I order. I might spend $10, I might spend $20
4. I'm only concerned about the food, so no more than $10.

**Comment by ahinkle** [comment]
> Do you want to eat meat?

1.  Maybe some lean proteins but nothing heavy.
2.  I'm feeling steak and BBQ.
3.  No way. Animals in my plate? Thanks but no thanks.
4. Yes, even better if they're in a taco or bowl of noodles.

**Comment by DaltonMcCleery** [comment]
> Ethnicity?

1. Mexican
2. Caucasian
3. Asian
4. Prefer not to say

**Comment by DaltonMcCleery** [comment]
> In terms of spicy, how much of a wimp are you?

1. Baby (mild only)
2. Newborn (mild - medium)
3. Adult (medium - hot)
4. Indepentant woman who don't need no man (Flaming Hot)

**Comment by DaltonMcCleery** [comment]
> Alcohol?

1. Yes please
2. Hard Liquor
3. Water-only
4. Fruity Drinks

**Comment by DaltonMcCleery** [comment]
> What is the chemical formula for Table Salt?

1. N2
2. CO2
3. NaCl
4. H2O

**Comment by DaltonMcCleery** [comment]
> What kind of atmosphere do you prefer?

1. My living room
2. Outdoor seating
3. The one that I can breathe
4. Dimly-lit Dungeons

**Comment by ahinkle** [comment]
> What side of Evansville do you prefer?

1. East Side
2. West Side
3. Downtown
